[package]
name = "weather"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
dotenv = "*"
dotenv_macros = "*"
hyper = "*"
or-iter = {git = "https://github.com/archer884/or-iter.git"}
serde = "*"
serde_derive = "*"
serde_json = "*"
